export const ProductsData = [
    {
        p_name: "Kettle",
        p_price: 1200,
        p_img: "https://m.media-amazon.com/images/I/61fgjj0QH-S._SL1500_.jpg",
        p_order: 10,
        id : 10,
      },
      {
        p_name: "Alexa Smart Homes",
        p_price: 2000,
        p_img: "https://m.media-amazon.com/images/I/61EXU8BuGZL._SL1100_.jpg",
        p_order: 1,
        id : 1,
      },
      {
        p_name: "Camera",
        p_price: 5000,
        p_img: "https://m.media-amazon.com/images/I/61MFkAyzeRL._SL1000_.jpg",
        p_order: 2,
        id : 2,
      },
      {
        p_name: "SanDisk",
        p_price: 600,
        p_img: "https://m.media-amazon.com/images/I/61DjwgS4cbL._SL1500_.jpg",
        p_order: 3,
        id : 3,
      },
      {
        p_name: "Logitec Mouse",
        p_price: 500,
        p_img: "https://m.media-amazon.com/images/I/51kdFjyPRAL._SL1500_.jpg",
        p_order: 4,
        id : 4,
      },
      {
        p_name: "KeyBoard",
        p_price: 700,
        p_img: "https://m.media-amazon.com/images/I/71XlOI9x+vL._SL1500_.jpg",
        p_order: 5,
        id : 4,
      },
       {
        p_name: "Head Set",
        p_price: 1300,
        p_img: "https://m.media-amazon.com/images/I/61l5JPGz16L._AC_SX615_SY462_.jpg",
        p_order: 6,
        id : 6,
      },
       {
        p_name: "Toaster",
        p_price: 800,
        p_img: "https://m.media-amazon.com/images/I/81lwRxNPPhL._SL1500_.jpg",
        p_order: 7,
        id : 7,
      }, 
      {
        p_name: "Mixer",
        p_price: 1500,
        p_img: "https://m.media-amazon.com/images/I/51PkufmNTUS._SL1080_.jpg",
        p_order: 8,
        id : 8,
      },
       {
        p_name: "Blender",
        p_price: 100,
        p_img: "https://m.media-amazon.com/images/I/41-5nd-r6bL._SL1000_.jpg",
        p_order: 9,
        id : 9,
      },
];
